// Valid 5-letter solution words (curated, common English words)
export const SOLUTION_WORDS: string[] = [
  'about', 'above', 'abuse', 'actor', 'acute', 'admit', 'adopt', 'adult', 'after', 'again',
  'agent', 'agree', 'ahead', 'alarm', 'album', 'alert', 'alien', 'align', 'alive', 'allow',
  'alone', 'along', 'alter', 'angel', 'anger', 'angle', 'angry', 'anime', 'ankle', 'apart',
  'apple', 'apply', 'arena', 'argue', 'arise', 'armor', 'array', 'arrow', 'aside', 'asset',
  'audio', 'audit', 'avoid', 'awake', 'award', 'aware', 'awful', 'babel', 'badge', 'badly',
  'baker', 'basic', 'basin', 'basis', 'batch', 'beach', 'beard', 'beast', 'begin', 'being',
  'below', 'bench', 'berry', 'bible', 'birth', 'black', 'blade', 'blame', 'bland', 'blank',
  'blast', 'blaze', 'bleed', 'blend', 'bless', 'blind', 'block', 'blood', 'bloom', 'blown',
  'board', 'boast', 'bonus', 'boost', 'booth', 'bound', 'brain', 'brand', 'brave', 'bread',
  'break', 'breed', 'brick', 'brief', 'bring', 'broad', 'broke', 'brook', 'brown', 'brush',
  'build', 'bunch', 'burst', 'buyer', 'cabin', 'cable', 'camel', 'candy', 'cargo', 'carry',
  'catch', 'cause', 'cease', 'chain', 'chair', 'chalk', 'chaos', 'charm', 'chart', 'chase',
  'cheap', 'check', 'cheek', 'cheer', 'chess', 'chest', 'chief', 'child', 'chunk', 'civic',
  'civil', 'claim', 'clash', 'class', 'clean', 'clear', 'clerk', 'click', 'cliff', 'climb',
  'cling', 'clock', 'clone', 'close', 'cloth', 'cloud', 'coach', 'coast', 'count', 'court',
  'cover', 'crack', 'craft', 'crane', 'crash', 'crazy', 'cream', 'creek', 'creep', 'crime',
  'crisp', 'cross', 'crowd', 'crown', 'crude', 'crush', 'curve', 'cycle', 'daily', 'dance',
  'death', 'debug', 'decay', 'delay', 'delta', 'demon', 'depot', 'depth', 'derby', 'devil',
  'diary', 'dirty', 'donor', 'doubt', 'dough', 'draft', 'drain', 'drama', 'drank', 'drawn',
  'dream', 'dress', 'drift', 'drink', 'drive', 'drone', 'drove', 'dying', 'eager', 'early',
  'earth', 'eight', 'elect', 'elite', 'ember', 'empty', 'enemy', 'enjoy', 'enter', 'entry',
  'equal', 'error', 'essay', 'ethic', 'event', 'every', 'exact', 'exist', 'extra', 'faith',
  'false', 'fancy', 'fatal', 'fault', 'feast', 'fence', 'fiber', 'field', 'fifth', 'fight',
  'final', 'first', 'fixed', 'flame', 'flash', 'flesh', 'fleet', 'float', 'flood', 'floor',
  'flour', 'fluid', 'flush', 'focal', 'focus', 'force', 'forge', 'forth', 'forum', 'found',
  'frame', 'frank', 'fraud', 'fresh', 'front', 'frost', 'fruit', 'fully', 'ghost', 'giant',
  'given', 'glass', 'globe', 'glory', 'glove', 'going', 'grace', 'grade', 'grain', 'grand',
  'grant', 'graph', 'grasp', 'grass', 'grave', 'great', 'greed', 'green', 'greet', 'grief',
  'grill', 'grind', 'gross', 'group', 'grove', 'grown', 'guard', 'guess', 'guest', 'guide',
  'guilt', 'haven', 'heart', 'heavy', 'hence', 'hobby', 'honor', 'horse', 'hotel', 'house',
  'human', 'humor', 'hyper', 'ideal', 'image', 'imply', 'index', 'indie', 'inner', 'input',
  'issue', 'ivory', 'jewel', 'joker', 'judge', 'juice', 'juicy', 'knack', 'kneel', 'knife',
  'knock', 'known', 'label', 'labor', 'lance', 'large', 'laser', 'later', 'laugh', 'layer',
  'learn', 'lease', 'least', 'leave', 'legal', 'lemon', 'level', 'light', 'limit', 'linen',
  'liver', 'local', 'lodge', 'logic', 'loose', 'lorry', 'lover', 'lower', 'loyal', 'lucky',
  'lunar', 'lunch', 'lying', 'magic', 'major', 'maker', 'manor', 'maple', 'march', 'match',
  'mayor', 'media', 'mercy', 'merit', 'metal', 'midst', 'might', 'minor', 'minus', 'model',
  'money', 'month', 'moral', 'motor', 'mount', 'mouse', 'mouth', 'movie', 'music', 'naked',
  'nerve', 'never', 'night', 'noble', 'noise', 'north', 'noted', 'novel', 'nurse', 'nylon',
  'ocean', 'offer', 'often', 'olive', 'onset', 'opera', 'orbit', 'order', 'organ', 'other',
  'ought', 'outer', 'owner', 'oxide', 'ozone', 'paint', 'panel', 'panic', 'paper', 'patch',
  'pause', 'peace', 'pearl', 'penny', 'phase', 'phone', 'photo', 'piano', 'piece', 'pilot',
  'pinch', 'pitch', 'pixel', 'pizza', 'place', 'plain', 'plane', 'plant', 'plate', 'plaza',
  'plead', 'pluck', 'plumb', 'plume', 'plump', 'plunge','plunk', 'point', 'polar', 'posit',
  'pound', 'power', 'press', 'price', 'pride', 'prime', 'print', 'prior', 'prize', 'probe',
  'proof', 'prose', 'proud', 'prove', 'pupil', 'queen', 'quest', 'queue', 'quick', 'quiet',
  'quote', 'radar', 'radio', 'raise', 'rally', 'range', 'rapid', 'ratio', 'reach', 'react',
  'ready', 'realm', 'rebel', 'reign', 'relax', 'renew', 'reply', 'rider', 'ridge', 'rifle',
  'right', 'rigid', 'risen', 'risky', 'rival', 'river', 'roast', 'robot', 'rocky', 'roman',
  'roost', 'rough', 'round', 'route', 'rover', 'royal', 'rugby', 'ruler', 'rural', 'saint',
  'salad', 'sauce', 'scale', 'scene', 'scope', 'score', 'sense', 'serve', 'setup', 'seven',
  'shade', 'shaft', 'shake', 'shall', 'shame', 'shape', 'share', 'shark', 'sharp', 'sheep',
  'sheer', 'sheet', 'shelf', 'shell', 'shift', 'shine', 'shirt', 'shock', 'shore', 'short',
  'shout', 'shown', 'sight', 'sigma', 'since', 'sixth', 'sixty', 'skill', 'skull', 'slave',
  'sleep', 'slice', 'slide', 'slope', 'small', 'smart', 'smell', 'smile', 'smoke', 'snake',
  'solar', 'solid', 'solve', 'sorry', 'south', 'space', 'spare', 'spark', 'speak', 'speed',
  'spend', 'spice', 'spike', 'spine', 'split', 'spoke', 'spoon', 'sport', 'spray', 'squad',
  'stack', 'staff', 'stage', 'stain', 'stake', 'stale', 'stall', 'stamp', 'stand', 'stark',
  'start', 'state', 'stays', 'steam', 'steel', 'steep', 'steer', 'stern', 'stick', 'stiff',
  'still', 'stock', 'stone', 'stood', 'store', 'storm', 'story', 'stout', 'stove', 'straw',
  'strip', 'stuck', 'study', 'stuff', 'style', 'sugar', 'suite', 'super', 'surge', 'swamp',
  'swear', 'sweep', 'sweet', 'swift', 'swing', 'sword', 'swore', 'sworn', 'syrup', 'table',
  'taste', 'teach', 'teeth', 'tempo', 'tense', 'terms', 'theme', 'thick', 'thief', 'thing',
  'think', 'third', 'thorn', 'those', 'three', 'threw', 'throw', 'thumb', 'tiger', 'tight',
  'timer', 'tired', 'title', 'today', 'token', 'topic', 'torch', 'total', 'touch', 'tough',
  'tower', 'toxic', 'trace', 'track', 'trade', 'trail', 'train', 'trait', 'trash', 'treat',
  'trend', 'trial', 'tribe', 'trick', 'tried', 'troop', 'truck', 'truly', 'trump', 'trunk',
  'trust', 'truth', 'tumor', 'tuner', 'twice', 'twist', 'ultra', 'uncle', 'under', 'union',
  'unite', 'unity', 'until', 'upper', 'upset', 'urban', 'usage', 'usual', 'utter', 'valid',
  'value', 'valve', 'vault', 'verse', 'video', 'vigor', 'vinyl', 'viral', 'virus', 'visit',
  'vista', 'vital', 'vivid', 'vocal', 'vodka', 'voice', 'voter', 'wagon', 'waste', 'watch',
  'water', 'weave', 'wedge', 'weigh', 'weird', 'wheat', 'wheel', 'where', 'which', 'while',
  'white', 'whole', 'whose', 'wider', 'witch', 'woman', 'world', 'worry', 'worse', 'worst',
  'worth', 'would', 'wound', 'wrath', 'wreck', 'write', 'wrong', 'wrote', 'yacht', 'yield',
  'young', 'youth', 'zebra',
];

// Additional valid guess words (accepted but never chosen as the answer)
export const EXTRA_GUESS_WORDS: string[] = [
  'adieu', 'aider', 'aisle', 'aorta', 'arose', 'attic', 'audio', 'badge', 'baste', 'batch',
  'beamy', 'beary', 'begat', 'berry', 'blase', 'bonny', 'bousy', 'braid', 'brace', 'brawn',
  'briar', 'briny', 'brisk', 'broth', 'buxom', 'canny', 'carat', 'cedar', 'chafe', 'champ',
  'chewy', 'chirp', 'choke', 'cigar', 'clair', 'cloche','commy', 'corgi', 'corny', 'coupe',
  'coyly', 'crank', 'crepe', 'crick', 'cupid', 'dandy', 'dealt', 'decor', 'deity', 'demit',
  'denim', 'dirac', 'ditto', 'dizzy', 'dodge', 'dowdy', 'dunce', 'eater', 'edict', 'eerie',
  'egoism', 'elate', 'elfin', 'email', 'ember', 'enema', 'ensue', 'envoy', 'epoch', 'ethyl',
  'euchar','exalt', 'exude', 'fairy', 'farce', 'fatty', 'fauna', 'femur', 'filer', 'filth',
  'finch', 'fizzy', 'fjord', 'flaky', 'flask', 'flint', 'flora', 'floss', 'flout', 'fluke',
  'foamy', 'foggy', 'foray', 'forge', 'foyer', 'frail', 'freak', 'freed', 'friar', 'fried',
  'frisk', 'fritz', 'frolic','frost', 'froth', 'froze', 'fungi', 'funky', 'furry', 'fuzzy',
  'gaily', 'gamma', 'gavel', 'giddy', 'gizmo', 'glare', 'glaze', 'gleam', 'glen',  'glib',
  'glint', 'gloat', 'gloom', 'glory', 'glued', 'glyph', 'gnarly','golem', 'gooey', 'goofy',
  'goose', 'gorge', 'gouge', 'gourd', 'gripe', 'grizz', 'grog',  'grout', 'growl', 'gruel',
  'guile', 'guise', 'gulch', 'gully', 'gumbo', 'guppy', 'gusty', 'gypsy', 'hadji', 'hasty',
  'hazel', 'heath', 'hefty', 'heist', 'hence', 'heron', 'hilly', 'hippo', 'homer', 'hooey',
  'horde', 'humid', 'humus', 'hyena', 'igloo', 'impel', 'inept', 'ingot', 'inlay', 'inner',
  'irate', 'ivory', 'jaunt', 'jazzy', 'jelly', 'jimmy', 'jolly', 'jumbo', 'jumpy', 'juror',
  'kazoo', 'kebab', 'khaki', 'kinky', 'kiosk', 'kitty', 'knave', 'knelt', 'koala', 'label',
  'lacey', 'llama', 'loopy', 'lousy', 'lucid', 'lurch', 'madam', 'mafia', 'manga', 'manor',
  'marsh', 'maxim', 'melee', 'mirth', 'mocha', 'mogul', 'moist', 'molar', 'mosey', 'mossy',
  'mummy', 'mural', 'nanny', 'navel', 'nudge', 'nutty', 'occam', 'oddly', 'offal', 'oomph',
  'optic', 'outdo', 'ovary', 'panda', 'pansy', 'papal', 'patsy', 'penny', 'pesto', 'petal',
  'picky', 'pious', 'pixel', 'pizza', 'plait', 'plaza', 'plied', 'poach', 'pooch', 'poppy',
  'potty', 'pricy', 'primp', 'privy', 'prom',  'prong', 'pudgy', 'puffy', 'puppy', 'pushy',
  'quack', 'qualm', 'quart', 'quash', 'query', 'quill', 'quirk', 'quota', 'rabbi', 'rabid',
  'ranco','ratty', 'raven', 'rayon', 'recap', 'rummy', 'salsa', 'salve', 'sandy', 'sauna',
  'saute', 'scald', 'scalp', 'scamp', 'scant', 'seize', 'shack', 'shall', 'shawl', 'shish',
  'skimp', 'skulk', 'skunk', 'slack', 'sleek', 'sleet', 'slept', 'sling', 'sloth', 'slump',
  'smite', 'smock', 'snail', 'snare', 'snide', 'snipe', 'snore', 'snout', 'solar', 'sonic',
  'spasm', 'spelt', 'spill', 'spook', 'spore', 'spout', 'squat', 'squid', 'staid', 'stair',
  'stale', 'staph', 'stave', 'steak', 'steep', 'stern', 'stoic', 'stomp', 'stork', 'stoup',
  'strut', 'stung', 'stunk', 'suave', 'suede', 'surly', 'swami', 'sweat', 'swill', 'tabby',
  'tacit', 'taffy', 'talon', 'tango', 'tangy', 'tarot', 'taunt', 'tepid', 'thump', 'tiara',
  'tic',  'tipsy', 'toast', 'trans', 'trawl', 'tripe', 'truce', 'trull', 'tubal', 'tulip',
  'tunic', 'tushy', 'twang', 'tweak', 'twill', 'twine', 'udder', 'undue', 'unfit', 'unlit',
  'unsay', 'unwed', 'upend', 'usher', 'usurp', 'vaunt', 'verge', 'vexed', 'vicar', 'viola',
  'viper', 'visor', 'vouch', 'vroom', 'wafer', 'wager', 'waist', 'waltz', 'warty', 'waste',
  'waxen', 'weary', 'wedge', 'whack', 'whirr', 'wince', 'winch', 'wined', 'wiper', 'woken',
  'wonky', 'woody', 'wreck', 'yodel', 'zippy', 'zloty',
];

export function getAllValidWords(): Set<string> {
  return new Set([...SOLUTION_WORDS, ...EXTRA_GUESS_WORDS]);
}

export function pickSolution(): string {
  return SOLUTION_WORDS[Math.floor(Math.random() * SOLUTION_WORDS.length)];
}